Repository githubtraining-sikebe-20230206-07/caption-this, pull requests merged in 2023-02, with the labels that each got.

#13 Update caption by tyamada0
  _slides/14-tyamada0.md
Labels: enhancement

#9 Update caption by sikebe-ms
  _slides/03-sikebe-ms.md
Labels: enhancement

#16 Add caption ryuinouegjc
  _slides/13-ryuinouegjc.md
Labels: documentation

#12 レビュー依頼【上村】
  _slides/11-nkamimura411.md
Labels: enhancement

#18 updating caption（レビュー依頼＿古本）
  _slides/06-afurumoto0206.md
Labels: bug

#17 updating caption
  _slides/05-NinomiyaAkira.md
Labels: enhancement

#10 Add caption myamai
  _slides/10-myamai.md
Labels: help wanted
